### ISSUE TITLE
ForEach and If directive changes

### ISSUE THREAD

**Issue by real-ashwin** [djsmith42/angular2_calendar#5]
# Calendar.js
## imports

---

import {Component, Template} from 'angular2/angular2';
import {CalendarCell} from 'components/calendar-cell/calendar-cell';
import {searchAllCells} from 'stores/registry';
import _ from '../../node_modules/lodash/index';
import {For, If} from 'angular2/directives';
## Directives

 directives: [
     For,
     If,
     CalendarCell
   ]
# Calendar-cell.js

---
## imports

import {Component, Template} from 'angular2/angular2';
import {addCell} from 'stores/registry';
import {BindingPropagationConfig} from 'angular2/src/change_detection/binding_propagation_config'
import {For, If} from 'angular2/directives';
## directives

directives: [
    For, If
   ]
# Calendar.html

---

the forEach template has to be changed
from : template="foreach: #day in days" 
to :  template="for #day of days"
# rx.js

---

[1] https://github.com/patternMiner/pattern_search/blob/master/package.json
[2] https://github.com/patternMiner/pattern_search/blob/master/index.html

Thanks.

**Comment by real-ashwin** [comment]
This project was not working due to recent Angular2 changes. I tried fixing it; see my changes above. When I wrote this in the original issue it did not show up. So commenting here.

**Comment by djsmith42** [comment]
@ashwinputhige Can you submit a pull request with these changes?

**Comment by real-ashwin** [comment]
All my attempts to create a pull request has failed(authentication error). Here's a patch - https://www.dropbox.com/sh/hmn83ycw91wzd57/AACPtrKv-hpsYwDEHe0195ria?dl=0 . Can you work with that?
Note that *if="!isLoaded"  wasn't working and so I created a new notLoaded variable.

**Comment by eHxBes** [comment]
Even with these changes it's not working :
_Error during instantiation of Token(AppComponentAnnotatedType)!. ORIGINAL ERROR: TypeError: undefined is not a function_

_zone.js:89 InstantiationError {keys: Array[3], message: "Error during instantiation of Token(AppComponentAn…NAL ERROR: TypeError: undefined is not a function"}_

I have also tried creating a pull-request with what @ashwinputhige modified, and I cannot create a branch to push the pull request
