### ISSUE TITLE
You had webpack there somewhere

### ISSUE THREAD

**Issue by Ciantic** [djsmith42/angular2_calendar#6]
I think in the presentation you had webpack there, have you managed to run Angular2 from webpack too?

I'm evaluating how to setup angular 2 stack for myself, and webpack is a huge jump forward from browserify I've used before.

Also I see webpack as a great companion when using TypeScript, which Angular 2 is built upon.

**Comment by djsmith42** [comment]
I didn't try to get Angular2 to work with webpack. Sorry.
